language: java
matrix:
    - ANDROID_SDKS=android-7             ANDROID_TARGET=android-7   ANDROID_ABI=armeabi
    - ANDROID_SDKS=android-8             ANDROID_TARGET=android-8   ANDROID_ABI=armeabi
    - ANDROID_SDKS=android-10            ANDROID_TARGET=android-10  ANDROID_ABI=armeabi
    - ANDROID_SDKS=android-16,sysimg-16  ANDROID_TARGET=android-16  ANDROID_ABI=armeabi-v7a
    - ANDROID_SDKS=android-17,sysimg-17  ANDROID_TARGET=android-17  ANDROID_ABI=armeabi-v7a
before_install:
    # install ia32-libs, see http://rkistner.github.io/android/2013/02/05/android-builds-on-travis-ci/
    - sudo apt-get update -qq
    - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
    # download the latest android sdk and unzip
    - wget http://dl.google.com/android/android-sdk_r22.2.1-linux.tgz
    - tar -zxf android-sdk_r22.2.1-linux.tgz
    - export ANDROID_HOME=`pwd`/android-sdk-linux
    - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
    - echo "sdk.dir=$ANDROID_HOME" > appcompat/local.properties
    - echo "sdk.dir=$ANDROID_HOME" > core/local.properties
    - echo "sdk.dir=$ANDROID_HOME" > example/local.properties
    - echo "sdk.dir=$ANDROID_HOME" > test/local.properties
    - echo "y" | android update sdk --filter platform-tools,android-17,extra-android-support,$ANDROID_SDKS --no-ui --force
    - echo "y" | android update lib-project --path ./appcompat --target android-17
    - echo "y" | android update project --path ./core --library ../appcompat --target android-17
    - echo "y" | android update test-project -m ../example -p ./test
    # Make sure the emulator has started before running tests
    - ./wait_for_emulator
    - cd test

script:
    - ant debug
    - ant install
    - ant test

